name 'mb_spring'
maintainer 'Justin Mitchusson'
maintainer_email 'jmitchusson23@gmail.com'
license 'All Rights Reserved'
description 'Installs and deploys a sample Spring web app.'
long_description 'Installs and deploys a sample Spring web app.'
version '0.1.0'
chef_version '>= 12.1' if respond_to?(:chef_version)
 issues_url 'https://github.com/jmitchusson/practice_chef/issues'
 source_url 'https://github.com/jmitchusson/practice_chef/mb_spring'
